---

- name: Compliance task OS
  debug:
    msg: "Linux Distribution: {{ ansible_distribution }} {{ ansible_distribution_major_version }}, version {{ ansible_distribution_version }}"

- name: Verify all required variables are defined
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{ required_vars }}"

- include: amazon_linux_1.yml
  when: (ansible_distribution == "Amazon" and 
          (ansible_distribution_major_version == "1" or ansible_distribution_version == "2018.03")) or
        (ansible_distribution is regex('^CentOS.*') and ansible_distribution_version is regex('^6.*'))

- include: amazon_linux_2.yml
  when: (ansible_distribution == "Amazon" and 
          (ansible_distribution_major_version == "2" or ansible_distribution_version == "(Karoo)")) or
        (ansible_distribution is regex('^CentOS.*') and ansible_distribution_version is regex('^7.*'))
